In [1]:
import numpy as np
import pandas as pd

In [12]:
flats = pd.read_csv("C:\\Users\\Dell\\campusx_badhiya_wala_project_isi_folder_me_sab_h\\flats_cleaned.csv")
houses = pd.read_csv("C:\\Users\\Dell\\campusx_badhiya_wala_project_isi_folder_me_sab_h\\house_cleaned.csv")

In [13]:
df = pd.concat([flats,houses],ignore_index=True)

In [14]:
df = df.sample(df.shape[0],ignore_index=True)

In [15]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Dayanand Colony,flat,ss residency,0.48,5333.0,900.0,Carpet area: 100 (83.61 sq.m.),3,2,2,not available,"1418, Dayanand Colony, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Hanuman Mandir', 'Dental Health Centre', 'No...","Prime location, 400 mtrs from main railway roa...",[],"['Security / Fire Alarm', 'False Ceiling Light...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
1,3 BHK Flat in Sector 103 Gurgaon,flat,ansal housing highland park,1.10,6242.0,1762.0,Super Built up area 1762(163.7 sq.m.)Built Up ...,3,3,3+,not available,"Tower 1, Sector 103 Gurgaon, Gurgaon, Haryana",7.0,North-East,0 to 1 Year Old,"['Dr. Hitesh Dawar', 'Bhardwaj Hospital', 'R K...",This 3 bhk flat is located in ansal housing hi...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,1 BHK Flat in Sector 83 Gurgaon,flat,sapphire eighty three,0.65,9286.0,700.0,Built Up area: 700 (65.03 sq.m.),1,1,0,not available,"Sector 83, Sector 83 Gurgaon, Gurgaon, Haryana",6.0,NaN,undefined,"['S.R.S. Hospital and Critical Care Unit', 'Or...",1bhk multistorey apartment for resale in sapph...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
3,3 BHK Flat in Sector 33 Gurgaon,flat,unitech the residences,1.35,8737.0,1545.0,Super Built up area 1545(143.54 sq.m.),3,4,2,servant room,"701, Sector 33 Gurgaon, Gurgaon, Haryana",8.0,North-East,5 to 10 Year Old,"['Huda Metro Station', 'Raheja Mall', 'Delhi G...",This 3 bhk apartment is available for sale in ...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."
4,4 BHK Flat in Sector 113 Gurgaon,flat,m3m capital,3.25,14142.0,2298.0,Carpet area: 2298 (213.49 sq.m.),4,4,3+,"pooja room,study room,servant room","Sector 113 Gurgaon , Gurgaon, Haryana",34.0,NaN,Dec 2025,"['Phase 2 Metro Station', 'Global Foyer Mall',...",Check out this 4 bhk apartment for sale in m3m...,"['4 AC', '1 Chimney', '1 Modular Kitchen', 'No...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN

In [18]:
df.to_csv('gurgaon_properties.csv',index=False)